name: Soma Script

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          WX_APP_ID: ${{ secrets.WX_APP_ID }}
          WX_SECRET_ID: ${{ secrets.WX_SECRET_ID }}
          WX_KF_ACCOUNT: ${{ secrets.WX_KF_ACCOUNT }}
          WX_NICK_NAME: ${{ secrets.WX_NICK_NAME }}
          WX_PASSWORD: ${{ secrets.WX_PASSWORD }}
          WX_TOUSER: ${{ secrets.WX_TOUSER }}
        run: python your_script.py
